### ISSUE TITLE
API documentation / homepage style / consistency with FE updates

### ISSUE THREAD

**Issue by laurenlucero** [Black-Stories-Matter/black_stories_matter_api#20]
Documentation
- [x] review and update README as needed
- [x] review and update CONTRIBUTING as needed
- [x] add any issues that could be good for an open-source contributor

Style/UI
- [x] add 1em margin to body
- [x] add break between the first two sentences
- [x] change footer background color to #181818
- [x] change footer button text to 'View All Books' (remove other View All button)
- [x] add button to return to API home to footer

Consistency
- [x] edit GitHub link to go to Organization page instead of FE repo
- [x] add a link to go to FE on Heroku
- [x] change All Books in Database body wording to 'Click any book for more information!' to match FE
- [x] 'This project was started and is maintained by'

**Comment by laurenlucero** [comment]
@kristastadler these are my only suggestions/requests for the API before we send it open source. let me know if you have any questions/concerns!

**Comment by kristastadler** [comment]
Done! Great suggestions here, thanks, @laurenlucero
